server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.217.130:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
    generate‐ddl: true
  rabbitmq:
    host: 192.168.217.130
  redis:
    host: 192.168.217.130
jwt:
  config:
    key: itcast
    ttl: 3600000
eureka: # 配置Eureka地址
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true


